server:
  port: ${PORT:8080}

spring:
  application:
    name: FlashSale

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/flashsale}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Mylearn123@}

  data:
    redis:
      host: ${REDIS_HOST:nimble-grandfather-stem-84138.db.redis.io}
      port: ${REDIS_PORT:13069}
      password: ${REDIS_PASSWORD:p25Qyr5l0ePds4M1cZQQAaIzNpb40xBr}
      ssl: ${REDIS_SSL:false}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
